const STORE={checkoutUrl:"",orderEmail:"TinkJenine1234@gmail.com"};
const products=[
{id:"peppermint-reset",name:"Peppermint Reset",cat:"clocked",label:"Clocked Out",notes:"Peppermint · Eucalyptus",desc:"A crisp, cooling aromatic soak made for tired feet, long shifts, and the moment your shoes finally come off.",featured:1,ribbon:"After-work favorite",a:"#dce3d3",b:"#72836b",s:"rgba(38,79,52,.55)"},
{id:"open-air",name:"Open Air Eucalyptus",cat:"clocked",label:"Clocked Out",notes:"Eucalyptus · Fresh greens",desc:"A strong eucalyptus aroma that makes the whole bath feel fresh, bright, and open—especially after a hot South Florida day.",featured:1,ribbon:"Fresh reset",a:"#c5d8ca",b:"#4f7567",s:"rgba(27,78,60,.55)"},
{id:"tea-tree",name:"Tea Tree Tingle",cat:"clocked",label:"Clocked Out",notes:"Tea tree · Cool mint",desc:"Fresh tea tree and a cool green profile create a clean, energizing bath with a lively tingle and smooth finish.",a:"#d7e3dc",b:"#77958a",s:"rgba(39,85,70,.5)"},
{id:"citrus-overload",name:"Citrus Overload",cat:"clocked",label:"Clocked Out",notes:"Orange · Lemon",desc:"Bright orange and lemon fragrance for the kind of bath that feels like opening every window in the house.",a:"#f3dcc0",b:"#d88d48",s:"rgba(163,82,28,.5)"},
{id:"raspberry-lemon",name:"Raspberry Lemon Drop",cat:"clocked",label:"Clocked Out",notes:"Raspberry · Lemon",desc:"Tart lemon and juicy raspberry balance each other in a vivid soak made for changing the mood fast.",a:"#edccd4",b:"#c65a77",s:"rgba(133,38,69,.5)"},
{id:"strawberry-lemonade",name:"Strawberry Lemonade",cat:"clocked",label:"Clocked Out",notes:"Strawberry · Lemon · Vitamin E",desc:"A sweet-tart fruit profile with an extra touch of vitamin E for skin that feels soft after the fizz is finished.",a:"#f2d6d3",b:"#d57575",s:"rgba(141,49,56,.48)"},
{id:"purple-dream",name:"Purple Dream",cat:"dnd",label:"Do Not Disturb",notes:"Lavender · Vanilla · Shimmer",desc:"A slow, fragrant blend of lavender and warm vanilla, handcrafted for evenings when the day has asked enough of you.",featured:1,ribbon:"Signature soak",a:"#d8c7df",b:"#806087",s:"rgba(72,42,81,.52)"},
{id:"night-night",name:"Night Night Lavender",cat:"dnd",label:"Do Not Disturb",notes:"Lavender · Dried buds",desc:"Classic lavender, soft purple shimmer, and dried buds turn warm water into an unmistakably evening kind of ritual.",featured:1,ribbon:"Evening favorite",a:"#ddd0e5",b:"#8a72a2",s:"rgba(78,56,105,.48)"},
{id:"chamomile",name:"Chamomile Bliss",cat:"dnd",label:"Do Not Disturb",notes:"Chamomile · Soft florals",desc:"A gentle golden bath dotted with chamomile flowers and built for quiet, softness, and absolutely nowhere else to be.",a:"#eee6c9",b:"#c7aa61",s:"rgba(126,97,28,.42)"},
{id:"mellow-out",name:"Mellow Out",cat:"dnd",label:"Do Not Disturb",notes:"Orange · Sandalwood",desc:"Soft citrus warmed by sandalwood: bright enough to lift the room, grounded enough to slow it back down.",a:"#ead5bb",b:"#9d7450",s:"rgba(101,67,35,.48)"},
{id:"sweet-wood",name:"Sweet Wood",cat:"dnd",label:"Do Not Disturb",notes:"Vanilla · Sandalwood",desc:"Creamy vanilla meets dry sandalwood in a warm, softly sweet fragrance that feels polished rather than sugary.",a:"#eadfce",b:"#9a7b65",s:"rgba(97,68,49,.45)"},
{id:"tingling-nights",name:"Tingling Nights",cat:"dnd",label:"Do Not Disturb",notes:"Lavender · Tea tree",desc:"Lavender softens the edges while tea tree brings a fresh, lightly tingling finish to the nighttime bath.",a:"#d7d3e1",b:"#6d7790",s:"rgba(53,62,94,.46)"},
{id:"romantic-rose",name:"Romantic Rose Petal",cat:"main",label:"Main Character Bath",notes:"Rose · Real petals",desc:"Deep rose fragrance and real petals create the kind of bath that deserves candles, music, and a locked door.",featured:1,ribbon:"Floral favorite",a:"#edc9d0",b:"#b85a72",s:"rgba(125,38,62,.52)"},
{id:"jasmine",name:"Jasmine Flower",cat:"main",label:"Main Character Bath",notes:"Jasmine · Soft shimmer",desc:"A confident white-floral fragrance with subtle shimmer, made for elegant baths and late-night main-character energy.",featured:1,ribbon:"Elegant floral",a:"#eee2d2",b:"#b5a37e",s:"rgba(105,85,46,.42)"},
{id:"renew",name:"Renew",cat:"main",label:"Main Character Bath",notes:"Cherry blossom · Vanilla",desc:"Airy cherry blossom and warm vanilla create a soft spring fragrance with a romantic, polished finish.",featured:1,ribbon:"Giftable favorite",a:"#f0d5da",b:"#c27b8f",s:"rgba(141,65,89,.44)"},
{id:"strawberries-cream",name:"Strawberries & Cream",cat:"main",label:"Main Character Bath",notes:"Strawberry · Vanilla",desc:"Ripe strawberry and creamy vanilla turn bath time into dessert without making the fragrance feel childish.",a:"#f0ced5",b:"#c35f79",s:"rgba(137,39,64,.5)"},
{id:"berries-cream",name:"Very Berries & Cream",cat:"main",label:"Main Character Bath",notes:"Strawberry · Blueberry · Raspberry · Vanilla",desc:"A plush berry blend rounded with vanilla for a colorful, sweet, generously scented bath.",a:"#d7bfd7",b:"#934e7b",s:"rgba(83,31,75,.52)"},
{id:"very-berry",name:"Very Very Berry",cat:"main",label:"Main Character Bath",notes:"Strawberry · Blueberry · Raspberry",desc:"Full-volume fruit fragrance with no apology: bright berries, saturated color, and a bath that refuses to be background scenery.",a:"#d4b7d1",b:"#754d88",s:"rgba(72,30,86,.5)"},
{id:"blueberry",name:"Sweet Blueberry",cat:"main",label:"Main Character Bath",notes:"Blueberry · Sweet fruit",desc:"A juicy blueberry-forward bath with rich color and a fresh fruit finish that feels playful, vivid, and giftable.",a:"#c6c8dc",b:"#536691",s:"rgba(39,51,98,.52)"},
{id:"orange-cream",name:"Orange Cream",cat:"main",label:"Main Character Bath",notes:"Orange · Vanilla",desc:"Creamy vanilla smooths bright orange into a nostalgic, sunny fragrance that still feels grown-up and luxurious.",a:"#f0dcc5",b:"#d59756",s:"rgba(151,82,28,.46)"}
];
const state={filter:"featured",limit:8,cart:JSON.parse(localStorage.getItem("j9-cart")||"[]"),active:null,size:"Immersion",price:20};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const grid=$("#productGrid"),drawer=$("#drawer"),overlay=$("#overlay"),modal=$("#modal"),modalOverlay=$("#modalOverlay"),toast=$("#toast");
function list(){return state.filter==="featured"?products.filter(p=>p.featured):state.filter==="all"?products:products.filter(p=>p.cat===state.filter)}
function card(p){return `<article class="product" style="--light:${p.a};--dark:${p.b}"><button class="product-art" data-product="${p.id}" aria-label="View ${p.name}">${p.ribbon?`<span class="ribbon">${p.ribbon}</span>`:""}<i class="bomb" style="--a:${p.a};--b:${p.b};--speck:${p.s}"></i></button><div class="product-copy"><small>${p.label}</small><h3>${p.name}</h3><p>${p.notes}</p><div class="product-bottom"><span>From<strong>$11</strong></span><button class="quick" data-product="${p.id}" aria-label="Choose size for ${p.name}">+</button></div></div></article>`}
function render(){const a=list(),visible=a.slice(0,state.limit);grid.innerHTML=visible.map(card).join("");$("#showMore").hidden=visible.length>=a.length;$$('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product))}
function filter(name){state.filter=name;state.limit=8;$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===name));render()}
$$('[data-filter]').forEach(el=>el.onclick=()=>filter(el.dataset.filter));$("#showMore").onclick=()=>{state.limit+=8;render()};
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;state.active=p;state.size="Immersion";state.price=20;$("#modalCat").textContent=p.label;$("#modalName").textContent=p.name;$("#modalNotes").textContent=p.notes;$("#modalDesc").textContent=p.desc;$("#modalPrice").textContent="$20";$(".modal-art").style.setProperty("--light",p.a);$(".modal-art").style.setProperty("--dark",p.b);$("#modalBomb").style.cssText=`--a:${p.a};--b:${p.b};--speck:${p.s}`;$$('.sizes button').forEach(b=>b.classList.toggle('active',b.dataset.size==='Immersion'));modal.classList.add('open');modalOverlay.classList.add('open');document.body.classList.add('locked')}
function closeModal(){modal.classList.remove('open');modalOverlay.classList.remove('open');if(!drawer.classList.contains('open'))document.body.classList.remove('locked')}
$("#closeModal").onclick=closeModal;modalOverlay.onclick=closeModal;
$$('.sizes button').forEach(b=>b.onclick=()=>{$$('.sizes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.size=b.dataset.size;state.price=Number(b.dataset.price);$("#modalPrice").textContent=`$${state.price}`});
function add(item){state.cart.push({...item,key:`${item.id}-${Date.now()}`});save();notify(`${item.name} added`)}
$("#addProduct").onclick=()=>{if(!state.active)return;add({id:state.active.id,name:state.active.name,size:state.size,price:state.price,a:state.active.a,b:state.active.b});closeModal();openBag()};
$("#addTrio").onclick=()=>{add({id:"trio",name:"Three-Mood Immersion Trio",size:"3 full-size bombs",price:54,a:"#d6c0da",b:"#74557d"});openBag()};
function save(){localStorage.setItem('j9-cart',JSON.stringify(state.cart));renderBag()}
function renderBag(){$("#bagCount").textContent=state.cart.length;const box=$("#bagItems");if(!state.cart.length)box.innerHTML='<div class="empty">Your bath is still waiting for its main character.</div>';else{box.innerHTML=state.cart.map(i=>`<div class="bag-item"><i class="mini-bomb" style="--a:${i.a};--b:${i.b}"></i><div><strong>${i.name}</strong><small>${i.size} · $${i.price}</small></div><button class="remove" data-remove="${i.key}">Remove</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(i=>i.key!==b.dataset.remove);save()})}$("#subtotal").textContent=`$${state.cart.reduce((s,i)=>s+i.price,0)}`}
function openBag(){drawer.classList.add('open');overlay.classList.add('open');document.body.classList.add('locked')}
function closeBag(){drawer.classList.remove('open');overlay.classList.remove('open');if(!modal.classList.contains('open'))document.body.classList.remove('locked')}
$("#bagBtn").onclick=openBag;$("#closeBag").onclick=closeBag;overlay.onclick=closeBag;
$("#checkout").onclick=()=>{if(!state.cart.length)return notify('Your ritual bag is empty');if(STORE.checkoutUrl)return location.href=STORE.checkoutUrl;const lines=state.cart.map(i=>`- ${i.name} (${i.size}) $${i.price}`).join('%0D%0A');const total=state.cart.reduce((s,i)=>s+i.price,0);location.href=`mailto:${STORE.orderEmail}?subject=${encodeURIComponent("Canni-Bombs order request")}&body=Hi Jenine,%0D%0A%0D%0AI'd like to order:%0D%0A${lines}%0D%0A%0D%0ASubtotal: $${total}%0D%0A%0D%0APlease send me the Square/Wix checkout details. Thank you!`};
$("#emailForm").onsubmit=e=>{e.preventDefault();$("#formMsg").textContent="You're on the list. The first drop will be worth the wait.";e.target.reset()};
$("#menuBtn").onclick=()=>{const nav=prompt('Type where you want to go: collections, shop, story, or faq');const target=nav&&document.getElementById(nav.toLowerCase());if(target)target.scrollIntoView({behavior:'smooth'})};
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2400)}
document.onkeydown=e=>{if(e.key==='Escape'){closeModal();closeBag()}};$("#year").textContent=new Date().getFullYear();render();renderBag();