// Add the published Wix checkout or store URL here when it is ready.
const STORE_CONFIG = {
  checkoutUrl: "",
  orderEmail: "TinkJenine1234@gmail.com"
};

const products = [
  {id:"peppermint-reset",name:"Peppermint Reset",legacy:"Muscle Relieving Peppermint",category:"clocked",categoryLabel:"Clocked Out",notes:"Peppermint · Eucalyptus",desc:"A crisp, cooling aromatic soak made for tired feet, long shifts, and the moment your shoes finally come off.",featured:true,ribbon:"After-work favorite",a:"#dce3d3",b:"#72836b",speck:"rgba(38,79,52,.55)"},
  {id:"open-air-eucalyptus",name:"Open Air Eucalyptus",legacy:"Sinus Relief Eucalyptus",category:"clocked",categoryLabel:"Clocked Out",notes:"Eucalyptus · Fresh greens",desc:"A strong eucalyptus aroma that makes the whole bath feel fresh, bright, and open—especially after a hot South Florida day.",featured:true,ribbon:"Fresh reset",a:"#c5d8ca",b:"#4f7567",speck:"rgba(27,78,60,.55)"},
  {id:"tea-tree-tingle",name:"Tea Tree Tingle",legacy:"Tingling Tea Tree",category:"clocked",categoryLabel:"Clocked Out",notes:"Tea tree · Cool mint",desc:"Fresh tea tree and a cool green profile create a clean, energizing bath with a lively tingle and a smooth finish.",a:"#d7e3dc",b:"#77958a",speck:"rgba(39,85,70,.5)"},
  {id:"citrus-overload",name:"Citrus Overload",legacy:"Citrus Overload Orange Lemonade",category:"clocked",categoryLabel:"Clocked Out",notes:"Orange · Lemon",desc:"Bright orange and lemon fragrance for the kind of bath that feels like opening every window in the house.",a:"#f3dcc0",b:"#d88d48",speck:"rgba(163,82,28,.5)"},
  {id:"raspberry-lemon-drop",name:"Raspberry Lemon Drop",legacy:"Uplifting Raspberry Lemon Drop",category:"clocked",categoryLabel:"Clocked Out",notes:"Raspberry · Lemon",desc:"Tart lemon and juicy raspberry balance each other in a playful, vivid soak made for changing the mood fast.",a:"#edccd4",b:"#c65a77",speck:"rgba(133,38,69,.5)"},
  {id:"strawberry-lemonade",name:"Strawberry Lemonade",legacy:"Soft Skin Strawberry Lemonade",category:"clocked",categoryLabel:"Clocked Out",notes:"Strawberry · Lemon · Vitamin E",desc:"A sweet-tart fruit profile with an extra touch of vitamin E for skin that feels soft after the fizz is finished.",a:"#f2d6d3",b:"#d57575",speck:"rgba(141,49,56,.48)"},
  {id:"purple-dream",name:"Purple Dream",legacy:"Purple Dream Lavender Vanilla",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Lavender · Vanilla · Shimmer",desc:"A slow, fragrant blend of lavender and warm vanilla, handcrafted for evenings when the day has asked enough of you.",featured:true,ribbon:"Signature soak",a:"#d8c7df",b:"#806087",speck:"rgba(72,42,81,.52)"},
  {id:"night-night-lavender",name:"Night Night Lavender",legacy:"Night Night Lavender",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Lavender · Dried buds",desc:"Classic lavender, soft purple shimmer, and dried buds turn warm water into an unmistakably evening kind of ritual.",featured:true,ribbon:"Evening favorite",a:"#ddd0e5",b:"#8a72a2",speck:"rgba(78,56,105,.48)"},
  {id:"chamomile-bliss",name:"Chamomile Bliss",legacy:"Chamomile Bliss Bomb",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Chamomile · Soft florals",desc:"A gentle golden bath dotted with chamomile flowers and built for quiet, softness, and absolutely nowhere else to be.",a:"#eee6c9",b:"#c7aa61",speck:"rgba(126,97,28,.42)"},
  {id:"mellow-out",name:"Mellow Out",legacy:"Mellow Out Orange Sandalwood",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Orange · Sandalwood",desc:"Soft citrus warmed by sandalwood: bright enough to lift the room, grounded enough to slow it back down.",a:"#ead5bb",b:"#9d7450",speck:"rgba(101,67,35,.48)"},
  {id:"sweet-wood",name:"Sweet Wood",legacy:"Sweet Wood Vanilla Sandalwood",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Vanilla · Sandalwood",desc:"Creamy vanilla meets dry sandalwood in a warm, softly sweet fragrance that feels polished rather than sugary.",a:"#eadfce",b:"#9a7b65",speck:"rgba(97,68,49,.45)"},
  {id:"tingling-nights",name:"Tingling Nights",legacy:"Tingling Nights Lavender Tea Tree",category:"dnd",categoryLabel:"Do Not Disturb",notes:"Lavender · Tea tree",desc:"Lavender softens the edges while tea tree brings a fresh, lightly tingling finish to the nighttime bath.",a:"#d7d3e1",b:"#6d7790",speck:"rgba(53,62,94,.46)"},
  {id:"romantic-rose",name:"Romantic Rose Petal",legacy:"Romantic Rose Petal",category:"main",categoryLabel:"Main Character Bath",notes:"Rose · Real petals",desc:"Deep rose fragrance and real petals create the kind of bath that deserves candles, music, and a locked door.",featured:true,ribbon:"Floral favorite",a:"#edc9d0",b:"#b85a72",speck:"rgba(125,38,62,.52)"},
  {id:"jasmine-flower",name:"Jasmine Flower",legacy:"Jasmine Flower",category:"main",categoryLabel:"Main Character Bath",notes:"Jasmine · Soft shimmer",desc:"A confident white-floral fragrance with subtle shimmer, made for elegant baths and late-night main-character energy.",featured:true,ribbon:"Elegant floral",a:"#eee2d2",b:"#b5a37e",speck:"rgba(105,85,46,.42)"},
  {id:"renew",name:"Renew",legacy:"Renew Sweet Cherry Blossom Vanilla",category:"main",categoryLabel:"Main Character Bath",notes:"Cherry blossom · Vanilla",desc:"Airy cherry blossom and warm vanilla create a soft spring fragrance with a romantic, polished finish.",featured:true,ribbon:"Giftable favorite",a:"#f0d5da",b:"#c27b8f",speck:"rgba(141,65,89,.44)"},
  {id:"strawberries-cream",name:"Strawberries & Cream",legacy:"Sweetbliss Strawberries and Cream",category:"main",categoryLabel:"Main Character Bath",notes:"Strawberry · Vanilla",desc:"Ripe strawberry and creamy vanilla turn bath time into dessert without making the fragrance feel childish.",a:"#f0ced5",b:"#c35f79",speck:"rgba(137,39,64,.5)"},
  {id:"berries-cream",name:"Very Berries & Cream",legacy:"Very Berries and Cream",category:"main",categoryLabel:"Main Character Bath",notes:"Strawberry · Blueberry · Raspberry · Vanilla",desc:"A plush berry blend rounded with vanilla for a colorful, sweet, generously scented bath.",a:"#d7bfd7",b:"#934e7b",speck:"rgba(83,31,75,.52)"},
  {id:"very-very-berry",name:"Very Very Berry",legacy:"Very Very Berry",category:"main",categoryLabel:"Main Character Bath",notes:"Strawberry · Blueberry · Raspberry",desc:"Full-volume fruit fragrance with no apology: bright berries, saturated color, and a bath that refuses to be background scenery.",a:"#d4b7d1",b:"#754d88",speck:"rgba(72,30,86,.5)"},
  {id:"sweet-blueberry",name:"Sweet Blueberry",legacy:"Sweet Blueberry Antioxidant",category:"main",categoryLabel:"Main Character Bath",notes:"Blueberry · Sweet fruit",desc:"A juicy blueberry-forward bath with rich color and a fresh fruit finish that feels playful, vivid, and giftable.",a:"#c6c8dc",b:"#536691",speck:"rgba(39,51,98,.52)"},
  {id:"orange-cream",name:"Orange Cream",legacy:"Sweet Citrus Orange Cream",category:"main",categoryLabel:"Main Character Bath",notes:"Orange · Vanilla",desc:"Creamy vanilla smooths bright orange into a nostalgic, sunny fragrance that still feels grown-up and luxurious.",a:"#f0dcc5",b:"#d59756",speck:"rgba(151,82,28,.46)"}
];

const state = {filter:"featured",visibleCount:8,cart:JSON.parse(localStorage.getItem("j9-cart")||"[]"),activeProduct:null,selectedSize:"Immersion",selectedPrice:20};
const productGrid=document.getElementById("productGrid"),loadMoreButton=document.getElementById("loadMore"),modal=document.getElementById("productModal"),modalOverlay=document.getElementById("modalOverlay"),cartDrawer=document.getElementById("cartDrawer"),drawerOverlay=document.getElementById("drawerOverlay"),toast=document.getElementById("toast");
function productCard(p){return `<article class="product-card" style="--card-light:${p.a};--card-dark:${p.b}"><button class="product-image" data-product="${p.id}" aria-label="View ${p.name}">${p.ribbon?`<span class="product-ribbon">${p.ribbon}</span>`:""}<span class="bomb" style="--bomb-a:${p.a};--bomb-b:${p.b};--speck:${p.speck}"></span></button><div class="product-body"><span class="product-category">${p.categoryLabel}</span><h3>${p.name}</h3><p class="product-notes">${p.notes}</p><div class="product-bottom"><span class="price-from">From<strong>$11</strong></span><button class="quick-add" data-product="${p.id}" aria-label="Choose size for ${p.name}">+</button></div></div></article>`}
function filteredProducts(){if(state.filter==="featured")return products.filter(p=>p.featured);if(state.filter==="all")return products;return products.filter(p=>p.category===state.filter)}
function renderProducts(){const list=filteredProducts(),visible=list.slice(0,state.visibleCount);productGrid.innerHTML=visible.map(productCard).join("");loadMoreButton.hidden=visible.length>=list.length;document.querySelectorAll("[data-product]").forEach(b=>b.addEventListener("click",()=>openProduct(b.dataset.product)))}
function setFilter(filter){state.filter=filter;state.visibleCount=8;document.querySelectorAll(".filter-btn").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));renderProducts()}
document.querySelectorAll(".filter-btn").forEach(b=>b.addEventListener("click",()=>setFilter(b.dataset.filter)));document.querySelectorAll(".collection-filter").forEach(l=>l.addEventListener("click",()=>setFilter(l.dataset.filter)));document.querySelectorAll("[data-footer-filter]").forEach(l=>l.addEventListener("click",()=>setFilter(l.dataset.footerFilter)));loadMoreButton.addEventListener("click",()=>{state.visibleCount+=8;renderProducts()});
function openProduct(id){const p=products.find(i=>i.id===id);if(!p)return;state.activeProduct=p;state.selectedSize="Immersion";state.selectedPrice=20;document.getElementById("modalCategory").textContent=p.categoryLabel;document.getElementById("modalTitle").textContent=p.name;document.getElementById("modalNotes").textContent=p.notes;document.getElementById("modalDesc").textContent=p.desc;document.getElementById("modalPrice").textContent="$20";document.getElementById("modalVisual").style.setProperty("--modal-light",p.a);document.getElementById("modalVisual").style.setProperty("--modal-dark",p.b);const mb=document.getElementById("modalBomb");mb.style.setProperty("--bomb-a",p.a);mb.style.setProperty("--bomb-b",p.b);mb.style.setProperty("--speck",p.speck);document.querySelectorAll(".size-option").forEach(o=>o.classList.toggle("active",o.dataset.size==="Immersion"));modal.classList.add("open");modalOverlay.classList.add("open");document.body.classList.add("no-scroll")}
function closeProduct(){modal.classList.remove("open");modalOverlay.classList.remove("open");if(!cartDrawer.classList.contains("open"))document.body.classList.remove("no-scroll")}
document.getElementById("closeModal").addEventListener("click",closeProduct);modalOverlay.addEventListener("click",closeProduct);document.querySelectorAll(".size-option").forEach(o=>o.addEventListener("click",()=>{document.querySelectorAll(".size-option").forEach(i=>i.classList.remove("active"));o.classList.add("active");state.selectedSize=o.dataset.size;state.selectedPrice=Number(o.dataset.price);document.getElementById("modalPrice").textContent=`$${state.selectedPrice}`}));
function addToCart(p,size,price){state.cart.push({id:`${p.id}-${size}-${Date.now()}`,productId:p.id,name:p.name,size,price,a:p.a,b:p.b,speck:p.speck});saveCart();showToast(`${p.name} · ${size} added`)}
document.getElementById("modalAdd").addEventListener("click",()=>{if(!state.activeProduct)return;addToCart(state.activeProduct,state.selectedSize,state.selectedPrice);closeProduct();openCart()});document.getElementById("addBundle").addEventListener("click",()=>{state.cart.push({id:`bundle-${Date.now()}`,productId:"three-mood-trio",name:"Three-Mood Immersion Trio",size:"3 full-size bombs",price:54,a:"#d6c0da",b:"#74557d",speck:"rgba(77,38,84,.48)"});saveCart();showToast("Three-Mood Immersion Trio added");openCart()});
function saveCart(){localStorage.setItem("j9-cart",JSON.stringify(state.cart));renderCart()}
function renderCart(){const box=document.getElementById("cartItems"),count=state.cart.length;document.getElementById("cartCount").textContent=count;if(!count)box.innerHTML=`<div class="empty-cart"><p>Your bath is still waiting for its main character.</p><a href="#shop" class="btn btn-secondary" onclick="closeCart()">Explore the scents</a></div>`;else{box.innerHTML=state.cart.map(i=>`<div class="cart-item"><div class="cart-thumb"><span class="bomb" style="--bomb-a:${i.a};--bomb-b:${i.b};--speck:${i.speck}"></span></div><div class="cart-info"><strong>${i.name}</strong><span>${i.size} · $${i.price}</span></div><button class="remove-item" data-remove="${i.id}">Remove</button></div>`).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{state.cart=state.cart.filter(i=>i.id!==b.dataset.remove);saveCart()}))}document.getElementById("cartSubtotal").textContent=`$${state.cart.reduce((s,i)=>s+i.price,0)}`}
function openCart(){cartDrawer.classList.add("open");drawerOverlay.classList.add("open");cartDrawer.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")}
function closeCart(){cartDrawer.classList.remove("open");drawerOverlay.classList.remove("open");cartDrawer.setAttribute("aria-hidden","true");if(!modal.classList.contains("open"))document.body.classList.remove("no-scroll")}
window.closeCart=closeCart;document.getElementById("cartButton").addEventListener("click",openCart);document.getElementById("closeCart").addEventListener("click",closeCart);drawerOverlay.addEventListener("click",closeCart);
document.getElementById("checkoutButton").addEventListener("click",()=>{if(!state.cart.length)return showToast("Your ritual bag is empty");if(STORE_CONFIG.checkoutUrl){window.location.href=STORE_CONFIG.checkoutUrl;return}const lines=state.cart.map(i=>`- ${i.name} (${i.size}) $${i.price}`).join("%0D%0A"),total=state.cart.reduce((s,i)=>s+i.price,0),subject=encodeURIComponent("Canni-Bombs order request"),body=`Hi Jenine,%0D%0A%0D%0AI'd like to order:%0D%0A${lines}%0D%0A%0D%0ASubtotal: $${total}%0D%0A%0D%0APlease send me the Square/Wix checkout details. Thank you!`;window.location.href=`mailto:${STORE_CONFIG.orderEmail}?subject=${subject}&body=${body}`});
document.querySelectorAll(".faq-question").forEach(b=>b.addEventListener("click",()=>{const item=b.parentElement,answer=item.querySelector(".faq-answer");item.classList.toggle("open");answer.style.maxHeight=item.classList.contains("open")?`${answer.scrollHeight}px`:"0px"}));document.getElementById("newsletterForm").addEventListener("submit",e=>{e.preventDefault();const email=new FormData(e.currentTarget).get("email");document.getElementById("formMessage").textContent=`You're on the list, ${email}. The first drop will be worth the wait.`;e.currentTarget.reset()});document.getElementById("menuButton").addEventListener("click",()=>{const c=window.prompt("Where would you like to go? Type: collections, shop, story, ritual, or faq");if(!c)return;const t=document.getElementById(c.toLowerCase());if(t)t.scrollIntoView({behavior:"smooth"})});
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2600)}
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeProduct();closeCart()}});document.getElementById("year").textContent=new Date().getFullYear();renderProducts();renderCart();
const visualFixes=document.createElement("script");visualFixes.src="visual-fixes.js?v=2";document.body.appendChild(visualFixes);
